# ################################
# Model: Whisper (Encoder-Decoder) + NLL + LoRA
# Augmentation: TimeDomainSpecAugment
# Authors: Peter Plantinga 2024, Adel Moumen 2022 & 2024, Titouan Parcollet 2022
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:speechbrain.utils.seed_everything [!ref <seed>]
trial_id: default
output_folder: !ref results/<trial_id>
output_wer_folder: !ref <output_folder>/
save_folder: !ref <output_folder>/save

# URL for the whisper model
whisper_hub: openai/whisper-tiny
whisper_folder: !ref pretrained_models/whisper_checkpoint

# Normalize the english inputs with
# the same normalization done in the paper
normalized_transcripts: True

# Data files

ckpt_interval_minutes: 1 # save checkpoint every N min

############################## Training Parameters #############################
freeze_encoder: True
number_of_epochs: 1
weight_decay: 0.01
lr_whisper: 1e-5
warmup_steps: 1
#precision: fp16 # bf16, fp16 or fp32
eval_precision: fp16
sampling_rate: 16_000

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# This setup works well with 1x 32GB GPU
batch_size: 16
test_batch_size: 16
#grad_accumulation_factor: 2
skip_nonfinite_grads: true

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 0.052 # about 78 tokens, increase if word deletions occur
test_beam_size: 8

# Lora configuration
lora_rank: 16

####################### Model Parameters #######################################

train_data_path: data/train.hdf5
valid_data_path: data/valid.hdf5
test_data_path: data/test.hdf5

train_loader_kwargs:
    batch_size: !ref <batch_size>
    shuffle: true

valid_loader_kwargs:
    batch_size: !ref <test_batch_size>

test_loader_kwargs:
    batch_size: !ref <test_batch_size>


epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>


whisper_pretrained: !new:speechbrain.lobes.models.huggingface_transformers.whisper.Whisper
    source: !ref <whisper_hub>
    freeze_encoder: !ref <freeze_encoder>
    save_path: !ref <whisper_folder>
    language: "english"
    task: "transcribe"
    sampling_rate: !ref <sampling_rate>

whisper: !new:speechbrain.nnet.adapters.AdaptedModel
    model_to_adapt: !ref <whisper_pretrained>
    adapter_class: !name:speechbrain.nnet.adapters.LoRA
    all_linear: True
    adapter_kwargs:
        rank: !ref <lora_rank>


modules:
    whisper: !ref <whisper>

############################## Decoding & optimiser ############################

whisper_opt_class: !name:torch.optim.AdamW
    lr: !ref <lr_whisper>
    weight_decay: !ref <weight_decay>

policy_temp_high: 1.0
policy_temp_low: 0.5
policy_temp_prob: 0.666
reward_weight: 1

policy: !new:utils.GFNPolicy
    model: !ref <whisper>
    temp_high: !ref <policy_temp_high>
    temp_low: !ref <policy_temp_low>
    temp_prob: !ref <policy_temp_prob>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>

use_buffer_prob: 0.25
buffer_size: 50
buffer_sim_tolerance: 0.25
replay_buffer: !new:utils.ReplayBuffer
    buffer_size: !ref <buffer_size>
    sim_tolerance: !ref <buffer_sim_tolerance>

loss_fn: !name:utils.modified_subtb_loss

lr_annealing_whisper: !new:speechbrain.nnet.schedulers.NoamScheduler
    lr_initial: !ref <lr_whisper>
    n_warmup_steps: !ref <warmup_steps>

############################## Logging and Pretrainer ##########################

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        whisper: !ref <whisper>
        scheduler_whisper: !ref <lr_annealing_whisper>
        counter: !ref <epoch_counter>
        replay_buffer: !ref <replay_buffer>
    custom_load_hooks:
      replay_buffer: !name:utils.buffer_load
    custom_save_hooks:
      replay_buffer: !name:utils.buffer_save

train_logger: !new:speechbrain.utils.train_logger.WandBLogger
    initializer: !name:wandb.init
        project: GFNASR
        name: !ref <trial_id>
        dir: !ref <output_folder>/wandb
        config:
            policy_temp_high: !ref <policy_temp_high>
            policy_temp_low: !ref <policy_temp_low>
            policy_temp_prob: !ref <policy_temp_prob>
            lr_whisper: !ref <lr_whisper>
            batch_size: !ref <batch_size>
            weight_decay: !ref <weight_decay>
            lora_rank: !ref <lora_rank>
            warmup_steps: !ref <warmup_steps>
            reward_weight: !ref <reward_weight>


wer_metric: !new:speechbrain.utils.metric_stats.ErrorRateStats

cer_metric: !new:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True

evaluate: true
